# Generated by Django 5.0.3 on 2024-12-21 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_equipment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='assigned_date',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='return_date',
        ),
        migrations.AlterField(
            model_name='equipment',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.user'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='condition',
            field=models.CharField(choices=[('New', 'New'), ('Used', 'Used')], max_length=50),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='type',
            field=models.CharField(max_length=255),
        ),
    ]
